# Generated by Django 3.1 on 2020-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='AlternateMobileno',
            field=models.IntegerField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Mobile',
            field=models.IntegerField(default=0.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Zipcode',
            field=models.IntegerField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='Zipcode',
            field=models.IntegerField(default=0.1),
            preserve_default=False,
        ),
    ]
