# Generated by Django 3.1 on 2020-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200821_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='AlternateMobileno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Zipcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Zipcode',
            field=models.CharField(max_length=50),
        ),
    ]
