# Generated by Django 3.1 on 2020-08-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.CharField(default=0.1, max_length=50),
            preserve_default=False,
        ),
    ]
