# Generated by Django 3.1 on 2020-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Pimage',
            field=models.ImageField(upload_to='image'),
        ),
    ]
