# Generated by Django 3.1 on 2020-08-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200822_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Pcolor',
            field=models.CharField(max_length=50),
        ),
    ]
